# Generated by Django 4.2 on 2026-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevariant',
            name='estimated_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
